spring.application.name=config-server

server.port=9999

eureka.client.service-url.defaultZone=http://localhost:5000/eureka/

spring.cloud.config.enabled=true
spring.profiles.active=git
spring.cloud.config.server.git.uri=https://github.com/Arunrajput1904/ConfigRepo.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.bootstrap=true
spring.cloud.config.server.git.force-pull=true

spring.cloud.config.server.git.timeout=5
eureka.instance.prefer-ip-address= true

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=config server loaded
info.app.description=good..............
info.app.version=1.0V

encrypt.key="webfuiwefhowehfowehgpoiwhgipwrhgpirwehgpiwr"